[build]
    command = "hugo --minify"
    publish = "public"
    functions = "functions"

[build.environment]
    HUGO_VERSION = "0.54.0/extended"

[context.production.environment]
    HUGO_ENV = "production"
    NODE_ENV = "production"

[context.deploy-preview]
    command = "hugo --buildDrafts --buildFuture"
